In [1]:
import torch

# Something for my understanding :
1. Tensor is n-d array
2. 0d -> scalar, 1d -> vector, 2d -> matrix and so on
3. Dimension of a tensor can be visualised till 3d. In general look at the number of brackets
4. Shape is number of elements in each dimension
5. Ways to create a tensor: Initialise all elements, tensor.rand(shape), torch.zeros(shape), torch.ones(shape), torch.arange(start, end, step)
6. Size is total number of elemets in the tensor. Multiply all numbers in shape to get size

## 1. Create a random tensor with shape `(7, 7)`.

In [7]:
x = torch.rand(7,7)
x, x.shape

(tensor([[0.3608, 0.0056, 0.9398, 0.8853, 0.5824, 0.5488, 0.3286],
         [0.3096, 0.1987, 0.7298, 0.1787, 0.7006, 0.4970, 0.5974],
         [0.1271, 0.8612, 0.8355, 0.0797, 0.1651, 0.6511, 0.1951],
         [0.8279, 0.9361, 0.6085, 0.6848, 0.4732, 0.1058, 0.3157],
         [0.2225, 0.0289, 0.0577, 0.5954, 0.9983, 0.3560, 0.3640],
         [0.7914, 0.9577, 0.5893, 0.3801, 0.0469, 0.1029, 0.1669],
         [0.6814, 0.7330, 0.2794, 0.3266, 0.6717, 0.8874, 0.2114]]),
 torch.Size([7, 7]))

## 2. Perform a matrix multiplication on the tensor from above with another random tensor with shape (1, 7)

In [9]:
y = torch.rand(1,7)
y, y.shape
# To multiply (7,7) with (1,7) we need to transpose the second tensor
z=torch.matmul(x,y.T)
z


tensor([[2.0504],
        [1.6364],
        [1.0075],
        [1.9962],
        [1.3870],
        [1.4471],
        [1.5334]])

## 3. Set the random seed to 0 and do exercises 1 & 2 over again.

In [15]:
seed = 0
torch.manual_seed(seed)
x=torch.rand(7,7)
x

torch.manual_seed(seed)
y=torch.rand(1,7)

z=torch.matmul(x,y.T)
z

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

## 4.Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? If there is then, set the GPU random seed to `1234`

In [3]:
import torch
random_seed = 1234
torch.cuda.manual_seed(random_seed)

x=torch.rand(7,7)
x

torch.cuda.manual_seed(random_seed)
y=torch.rand(1,7)

z=torch.matmul(x,y.T)
z


tensor([[2.1670],
        [2.3911],
        [1.8846],
        [2.1971],
        [2.2878],
        [2.1232],
        [1.1475]])

## 5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [6]:
import torch
torch.cuda.is_available()
#device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

torch.manual_seed(1234)
tensor1 = torch.rand(2,3)
torch.manual_seed(1234)
tensor2 = torch.rand(2,3)

tensor1gpu = tensor1.to(device)
tensor2gpu = tensor2.to(device)

tensor1gpu, tensor2gpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

## 6. Perform a matrix multiplication on the tensors you created in 5 (again, you may have to adjust the shapes of one of the tensors).

In [12]:
p = torch.matmul(tensor1gpu, tensor2gpu.T)
p, p.shape

(tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]], device='cuda:0'),
 torch.Size([2, 2]))

## 7. Find the maximum and minimum values of the output of 6.

In [13]:
p.max(), torch.min(p)

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

## 8. Find the maximum and minimum index values of the output of 6

In [16]:
p.argmin(), torch.argmax(p), p.argmax()

(tensor(1, device='cuda:0'),
 tensor(3, device='cuda:0'),
 tensor(3, device='cuda:0'))

## 9. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [17]:
random_seed =7
torch.manual_seed(random_seed)
tensor1 = torch.rand(1,1,1,10)
# tensor1, tensor1.shape

tensor_squeezed = tensor1. squeeze()

print(f"Original tensor is {tensor1} and shape is {tensor1.shape}")
print(f"Squeezed tensor is {tensor_squeezed} and shape is {tensor_squeezed.shape}")
# tensor_squeezed, tensor_squeezed.shape


Original tensor is tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) and shape is torch.Size([1, 1, 1, 10])
Squeezed tensor is tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) and shape is torch.Size([10])
