##00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
print("Hello I'm excited to learn PyTorch!")

Hello I'm excited to learn PyTorch!


In [2]:
!nvidia-smi

Tue Apr  8 01:48:17 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   51C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

## Creating tensors

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim
scalar.shape

torch.Size([])

In [6]:
# Get tensor back as python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3], [3,6,9], [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update randm numbers -> look at data -> update random numbers

In [18]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.6821, 0.7663, 0.9896, 0.3479],
        [0.3806, 0.4869, 0.3652, 0.5921],
        [0.8503, 0.3563, 0.0632, 0.4384]])

In [19]:
random_tensor.ndim

2

Image as a tensor : We store the pixel value in the tensor where you have a three dimensional tensor. The first 2D matrix is for red, second for green and third for blue. Inside each matrix there are 224 vectors and each vector has 224 values which represents the height and width of the image


In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [21]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Creare a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

# Creating a range of tensors and tensors-like


In [24]:
# Use torch.range() or torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors datatypes

**NOTE:** Tensor datatypes is on of the 3 big errors you will run into with PyTorch and deep learning:
1. Tensors not right datatype (some operations)
2. Tensors not right shape
3. Tensors not on the right device


In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0,9.0],
                               dtype=None, # what datatype is the tensor like float32 or float16. Speed decreases on increasing precision
                               device="cuda", # What device is your tensor on? Pytorch throws error if tensors on different devices
                               requires_grad=False )# tracking gradients(don't know what they are yet) with tensor operation
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [28]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [29]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [30]:
# float_32_tensor * int_32_tensor

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype (some operations) - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [31]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4181, 0.4350, 0.9751, 0.9872],
        [0.9831, 0.7893, 0.7442, 0.9777],
        [0.5816, 0.9201, 0.3218, 0.2423]])

In [32]:
# Find out details about some tensor

print(some_tensor)
print(f"Datatype of tensor;{some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4181, 0.4350, 0.9751, 0.9872],
        [0.9831, 0.7893, 0.7442, 0.9777],
        [0.5816, 0.9201, 0.3218, 0.2423]])
Datatype of tensor;torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include :
* addition
* Subtraction
* Multiplication(element-wise)
* division
* Matrix Multiplication

In [33]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [34]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [35]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [36]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [37]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that  performing matrix multiplication needs to satisfy

1. The **inner dimensions** must match
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`


In [38]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.8837, 0.6155],
        [1.2127, 0.8274]])

In [39]:
# Element wise multiplication

print(tensor, "*",  tensor)
print (f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [40]:
# Matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 209 µs, sys: 48 µs, total: 257 µs
Wall time: 2.38 ms


tensor(14)

In [41]:
# Matrix multiplication manually using a loop
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: user 455 µs, sys: 0 ns, total: 455 µs
Wall time: 532 µs


### one of the most common errors in deep learning is shape errors

In [42]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2], [3,4], [5,6]])
tensor_B = torch.tensor([[7,10], [8,11], [9,12]])

torch.mm(tensor_A, tensor_B.T) # torch.mm is an alias for matmul
torch.mm(tensor_A, tensor_B.T).shape



torch.Size([3, 3])

In [43]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [44]:
tensor_B.T.shape

torch.Size([2, 3])

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose

## finding the min, max, mean, sum, etc (temsor aggregation)

In [45]:
x = torch.arange(0,100,10)
x.dtype
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [47]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [48]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [49]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max


In [50]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [52]:
# Returns index of max value in the tensor
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but know the same memeory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [53]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [55]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

## reshaping it to 1,7 doesnt work because we try to squeeze 9 elemts to
## reshaping to 2,9 also doesnt work because then we need 18 elements
## reshaping to 9,1 works
## reshaping to 5,2 works

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [56]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:
# Changing z changes x because a view of a tensor shares the same memory as the original
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [58]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [61]:
# torch.squeeze() - removes al single dimensions from tensor
x_reshaped.shape, x_reshaped

(torch.Size([9, 1]),
 tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]))

In [63]:
x_squeezed = x_reshaped.squeeze()

In [62]:
x_reshaped.squeeze().shape

torch.Size([9])

In [65]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"New tensor: {x_unsqueezed}")
x_unsqueezed.shape

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


torch.Size([9, 1])

In [66]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
# permute is usually used with images

x_original = torch.rand(size=(224,224,3)) #[height, width,color_channels]

# Permute the tensor to rearrange the axis or dim
x_permuted = x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0

print(x_original.shape)
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [70]:
x_original[0,0,0] = 5813
x_original[0,0,0], x_permuted[0,0,0]
#changes made in the original tensor are also seen in the permuted tensor

(tensor(5813.), tensor(5813.))

## Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy


In [76]:
import torch
x= torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [77]:
x[0] #indexing on the zeroth dimension gives you what's inside the 0th dimension bracket

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
# Let's index on the middle bracket(dim=1)
x[0][0] # or x[0,0] - this means zeroth place of the zero dimension bracket when you are inside it

tensor([1, 2, 3])

In [82]:
# Index on the inner msot bracket (last dim)
x[0][2][2]

tensor(9)

In [83]:
# You can also use ":" to select "all" of a target dim
x[:,0]

tensor([[1, 2, 3]])

In [84]:
# Get all values of zero and first dim but only index 1 of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [85]:
# Get all values of zero dim but only 1 index value of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [86]:
# Get index 0 of 0th and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [87]:
# Index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library

PyTorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [6]:
#NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32) # warning: when converting numpy to pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [3]:
array.dtype

dtype('float64')

In [4]:
tensor.dtype

torch.float64

In [5]:
torch.arange(1.0,8.0).dtype

torch.float32

In [7]:
# Change the value of array, what will this do to the tensor?
array = array +1
array, tensor

# Nothing changes in the tensor. we get a new tensor in the memory

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [8]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

# Here also array reflects the data type of tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [9]:
# Change the tensor, what happens to numpy arary?
tensor = tensor + 1
tensor, numpy_tensor

# again tensor and array have different memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

how a neural network learns:

`Start with random numbers -> tensor operations -> update random numbers to try and make them better representations of data -> again -> again -> again -> again...`

to reduce the randomness in neural networks and pytorch comes the concept of a **random seed**

Essentially what the random seed does is flavour the randomness.

In [11]:
import torch

#create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B) # To check if tensors are equal or not


tensor([[0.4590, 0.3398, 0.5609, 0.9924],
        [0.1545, 0.6738, 0.0091, 0.3480],
        [0.6940, 0.6363, 0.7697, 0.3318]])
tensor([[0.6035, 0.0823, 0.4106, 0.7006],
        [0.1945, 0.9535, 0.1425, 0.7541],
        [0.6269, 0.9768, 0.7018, 0.9070]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [12]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)


print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch objects on the GPUs and making faster computations

GPUs = faster computation on numbers, thanks to CUDA, NVIDIA hardware + pytorch working behind the scenes to make everything hunky dory

from sre_constants import GROUPREF_UNI_IGNORE
### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires purchasing a GPU
3. Use Cloud computing - GCP, AWS, Azure, allow you to rent computers on cloud and access them

for 2,3 PyTorch + GPU drivers(CUDA) takes setting up to do. Refer to PyTorch setup documents

In [14]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### 2. check for GPU access with PyTorch

In [16]:
import torch
torch.cuda.is_available()

False

In [17]:
# Setup device agnostic code
# It is good practice to set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [18]:
# Count number of devices
torch.cuda.device_count()

0

## 3. Putting tensors (and models) on the GPU

 The reason that we want our tensors/models on the GPU is to do faster computations


In [20]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [21]:
# Move tensor to GPU(if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

In [22]:
# If tensor is on GPU, cant transform it to NumPy
# So first set it to the CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

# tensor would still remain on the gpu

array([1, 2, 3])